version: '3.3'
volumes:
  static:
  media:
  pg_data:


services:
  db:
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build/
  backend:
    depends_on:
      - frontend
      - db
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file: ../.env
    volumes:
      - static:/app/collected_static
      - media:/media
    command: bash -c "gunicorn --bind 0.0.0.0:8000 app.wsgi"
  nginx:
    depends_on:
      - backend
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
