version: '3.3'
volumes:
  static:
  media:


services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      # - ../frontend/:/app/result_build/
      - static:/app/result_build/
  backend:
    depends_on:
      - frontend
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static:/app/collected_static
      - media:/media
  nginx:
    depends_on:
      - backend
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/media
      - ../docs/:/usr/share/nginx/html/api/docs/
