# Generated by Django 4.2.2 on 2023-06-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='-', max_length=20, unique=True, verbose_name='tag'),
        ),
    ]
